### ISSUE TITLE
Bug question suivante

### ISSUE THREAD

**Issue by lhdevriendt** [edj-projets-web/devenir-espion#3]
Doit cliquer du deuxième coup sur la sélection de la langue avant de passer à la question suivante. 
Après, quand on clique sur la bonne traduction, on ne passe pas à la question suivante, on est bloqué à la question 2.

**Comment by julesbonnard** [comment]
Pour passer à la question suivante, il faut déclencher un évènement submit ````type="submit"```` qui valide un formulaire ````form````, dans lequel est contenu l'instruction suivante ````data-next="geographie"```` pour passer à la section Géographie, par exemple.
