### ISSUE TITLE
Transitions - Bug

### ISSUE THREAD

**Issue by MeganeDeAmorim** [edj-projets-web/devenir-espion#7]
Petit bug au niveau de la première transition (fin de la 1ere partie sur la culture g) => même en cliquant sur "Prêt" on ne passe pas à la 2e partie.
Et côté forme, la transition devrait avoir la même charte graphique que la page d'accueil (logo, cadre qui contient le petit texte, bouton "Je suis prêt")

**Comment by julesbonnard** [comment]
Fixé, mis à part le design sans header
